version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
#  group updates disabled until dependabot group updates run `go mod tidy`
#  https://github.com/dependabot/dependabot-core/issues/11046
#  groups:
#    actions:
#      patterns:
#      - "*"
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
#  groups:
#    root-deps:
#      patterns:
#      - "*"
- package-ecosystem: gomod
  directories:
  - /cmd/krane
  - /pkg/authn/k8schain
  - /pkg/authn/kubernetes
  schedule:
    interval: weekly
#  groups:
#    auxiliary-deps:
#      patterns:
#      - "*"
